### ISSUE TITLE
Problem automating two oscillators, one for each channel

### ISSUE THREAD

**Issue by kindohm** [jussi-kalliokoski/audiolib.js#39]
I'm having trouble getting an LFO to work on two oscillators. I'm automating the frequency of the oscillators. I'm writing the samples of one oscillator to the left channel and the samples of the other oscillator to the right channel.

The code below results in two oscillators generating normally with no apparent LFO automation. Any ideas?

``` js
function buildAudio() {
    audioDevice = audioLib.AudioDevice(audioCallback, channelCount);
    oscillator1 = audioLib.Oscillator(audioDevice.sampleRate, 440);
    oscillator2 = audioLib.Oscillator(audioDevice.sampleRate, 441);
    lfo1 = audioLib.Oscillator(audioDevice.sampleRate, 1);
    lfo2 = audioLib.Oscillator(audioDevice.sampleRate, 2);
    oscillator1.addAutomation('frequency', lfo1, .25, 'additiveModulation');
    oscillator2.addAutomation('frequency', lfo2, .55, 'additiveModulation');
}

function audioCallback(buffer, channelCount) {
    var l = buffer.length, current;

    for (current = 0; current < l; current += channelCount) {
        lfo1.generate();
        lfo2.generate();
        oscillator1.generate();
        oscillator2.generate();
        buffer[current] = oscillator1.getMix();
        buffer[current + 1] = oscillator2.getMix();
    }
}
```

**Comment by jussi-kalliokoski** [comment]
Hey there!

Yeah, the thing is that the automation API only works with the `.append()` function (due to the quite large overhead it would cause if it was applied for each `.generate()` or `.pushSample()`.

So, since you're working on single sample level, I'd suggest going with something like this...

First, ditch the automation part, and add this before the oscillator{1,2}.generate() part.

``` javascript

oscillator1.fm = lfo1.getMix() * .25;
oscillator2.fm = lfo2.getMix() * .55;

```

Regards,
Jussi

**Comment by kindohm** [comment]
Ah I didn't see the .fm property on the oscillator before. That's what I needed - thanks!
