### ISSUE TITLE
Timing of Automation

### ISSUE THREAD

**Issue by charlieroberts** [jussi-kalliokoski/audiolib.js#40]
Hi,

First, thank you for this library. Every time I think I need to add something to it I dig a little bit deeper and it's already in there. Really spectacular work.

I'm having problems with the timing of Automation objects. If I use a StepSequencer as the source for an Automation, and then apply that Automation to the frequency of an oscillator the timing has a lot of jitter to it. If I use preProcessing to do roughly the same thing, the timing is great and I don't hear any jitter.

I like the syntax of the Automation class and want to use it... I'm curious if I'm doing anything wrong or if anyone can back up my findings. Here's a simple script to test, just change the USE_AUTOMATION flag to hear the sequence with it on and off.

Thanks for any help! - Charlie

`````` javascript
<html>
    <head>
        <script src="js/audiolib.js"></script>
        <script>
        window.onload = function(){
            window.USE_AUTOMATION = true;

            dev = audioLib.AudioDevice(audioProcess, 2),

            window.osc = new audioLib.Oscillator(dev.sampleRate, 220);
            window.osc.waveShape = 'square';
            window.osc.mix = .1;

            window.mod = new audioLib.StepSequencer(dev.sampleRate, 250,  [120, 240, 120, 360], 0.0);

            if(USE_AUTOMATION) {
                window.osc.addAutomation("frequency", mod, 1, "assignment");
            }else{
                window.osc.addPreProcessing(preProcess);
            }
        }

        function preProcess() {
            window.mod.generate();
            this.frequency = window.mod.getMix();
        }

        function audioProcess(buffer, channelCount){
            if(window.USE_AUTOMATION) {
                window.mod.generateBuffer(buffer.length, channelCount);
            }
            window.osc.append(buffer, channelCount);
        };

        </script>
    </head>
    <body>  
    </body>
</html>```
``````

**Comment by jussi-kalliokoski** [comment]
I'm glad you like it!!!

Instead of 

``` javascript
window.mod.generateBuffer(buffer.length, channelCount);
```

try this:

``` javascript
window.mod.generateBuffer(buffer.length / channelCount);
```

The former creates a stereo buffer, whereas the automation buffer should be single channel. And since it's interleaved, what happens basically is that the automation gets applied at half the speed and half of the buffers get ignored. :)

Also, I'm trying to encourage using `Sink()` instead of `audioLib.AudioDevice`, because the `AudioDevice` is a legacy interface with a misnomer (since it's not really a device, or even a device interface), and I'm planning to deprecate it in the future. It works exactly the same as the `AudioDevice`, in fact the `AudioDevice` is just an alias of the `Sink` for backwards compatibility. :)

**Comment by charlieroberts** [comment]
That solved it... thanks! And I changed my code to use Sink :)

Thanks again for the quick response.

**Comment by jussi-kalliokoski** [comment]
No problem, glad to help! ^^
