### ISSUE TITLE
Sampler.loadWav performance

### ISSUE THREAD

**Issue by kindohm** [jussi-kalliokoski/audiolib.js#41]
I'm seeing some very slow load times when Sampler.loadWav is called on larger wave file samples. In my specific case I have 2-channel 44.1khz samples ranging from 128 KB in size to 844 KB. The 128kb sample takes about 4-5 seconds to load during loadWav(). My 844kb sample takes a very long time - more than a minute at least. Are the included codecs just not capable of dealing with larger samples?

**Comment by jussi-kalliokoski** [comment]
Yeah, the problem here is the memory speed in JS, a huge amount of time is spent just allocating the buffers (especially for the strings that contain the data). All of the loading should be done asynchronously with XHR, and then the sampler should stream through multiple buffers instead of one big buffer, similarly to how we have done the JS codecs ([mp3](https://github.com/ofmlabs/jsmad) [alac](https://github.com/ofmlabs/alac.js) [flac](https://github.com/ofmlabs/flac.js)). This would, however, require more advanced SRC features, etc, so it will take some time, but it's on the plan to make it possible to use our codec suite, [aurora.js](https://github.com/jensnockert/aurora.js) alongside with audiolib.js, so you can load even big samples and in the format you prefer.

**Comment by jussi-kalliokoski** [comment]
So far, on Chrome, the problem is even more escalated, if you try to load a sample too big, the page just freezes.

**Comment by kindohm** [comment]
Ok - thanks for the feedback. I figured that that was the case.
