### ISSUE TITLE
problems under os x

### ISSUE THREAD

**Issue by charlieroberts** [jussi-kalliokoski/audiolib.js#60]
I updated some system software this morning and am suddenly experiencing problems in Chrome 20.0.1105.0 dev under OS X 10.6.8.  When I ran an older version of audiolib.js (not too old... maybe 2.5 weeks) I get an error upon initialization saying "No audio sink available". When I update audiolib.js to use the new sink.js changes, audio starts but clicks every half second or so and has a low level of noise throughout, whenever a sink is created.

There are also some problems in Firefox with erratic behavior after the most recent sink.js update.

Anyone else on OS X who is experiencing problems? Or who is running the most recent changes and is -not- experiencing problems? Thanks! - Charlie

**Comment by charlieroberts** [comment]
Hmmm... sorry, maybe a false alarm. It appears to work fine under the stable version of Chrome (18.0.1025.163). I do get the same weird behavior that I got in Firefox using the recent changes to sink.js but I suspect that this has something to do with my code and how I do timing using sinks.

I don't really think it's worth exploring why it doesn't work in the dev version of Chrome on an older version of OS X after some arbitrary system updates, so I'm going to close this.

**Comment by jussi-kalliokoski** [comment]
To be sure, could you try downloading the latest version from downloads and seeing if the problems are still there?

A while back, there was a problem in sink.js that it would incorrectly fall back to using Data URI Audio elements instead of the web audio API, the issue you were having sounded exactly like that. I haven't tried Chrome 20 yet, so it might as well be that something changed in the Web Audio API that is causing the sink initialization to fail, hence using the Data URI fallback.

What kind of erratic behavior are you seeing on Firefox? There was a latency optimization I recently turned off in favor of less CPU cycles used (and hence less of those annoying "Page not responding" popups), so overall experience on Firefox should now be better, although the latency is a bit higher.
