### ISSUE TITLE
What is Math.sqrt(a, b) ?

### ISSUE THREAD

**Issue by dsego** [jussi-kalliokoski/audiolib.js#74]
https://github.com/jussi-kalliokoski/audiolib.js/blob/master/src/processors/fft.js#L417

**Comment by jussi-kalliokoski** [comment]
Agh, good catch. This is why we need unit tests. :D

**Comment by dsego** [comment]
Not sure if appropriate to ask here. Can you explain bSi to me or point me to a resource where this is explained?

edit: I guess to get power per hertz?

**Comment by jussi-kalliokoski** [comment]
Yeah, it's the normalization factor, so that for example the magnitude of an impulse doesn't depend on the buffer size, mapping sample data [1, 0, 0, 0] and [1, 0, 0, 0, 0] to [1, 1, 1, 1] and [1, 1, 1, 1, 1] in magnitude, because the FFT itself doesn't normalize.

TBH `bSi` is not a very good variable name for a normalization factor though, as it just refers to bufferSize, I should probably fix that.

**Comment by dsego** [comment]
Thanks.
