### ISSUE TITLE
Install it on Mac OS X

### ISSUE THREAD

**Issue by SamDecrock** [jussi-kalliokoski/audiolib.js#79]
Hi,

I've tried installing this using 

```
npm install audiolib
```

on my Mac, but it fails when installing `cubeb`. I've tried installing cubeb, but I can't seem to get it working.
Can someone give me more instructions on how to do this?

Thx

**Comment by knappe** [comment]
Same problem.

749 error Tell the author that this fails on your system:
749 error     node-gyp rebuild
749 error You can get their info via:
749 error     npm owner ls cubeb
749 error There is likely additional logging output above.
750 error System Darwin 12.3.0
751 error command "node" "/usr/local/bin/npm" "install" "audiolib"

**Comment by knappe** [comment]
I've contacted the maintainer to see if there is some kind of resolution.  I was able to manually install cubeb by hand via 

https://github.com/kinetiknz/cubeb/blob/master/INSTALL

but that didn't seem to clear up the issues with npm.

**Comment by jussi-kalliokoski** [comment]
Sorry for taking so long with this, guys, I've been really busy!

The correct bug for this is kinetiknz/cubeb#20 , since this isn't really related to node-cubeb. node-cubeb just dynamically links to cubeb and unfortunately currently cubeb is a pretty hard target to link to since it doesn't automatically register itself to the linker, etc.

Of course this raises the important question of whether cubeb should be a requirement for audiolib.js... If you think it shouldn't, feel free to open a new bug and we'll discuss, but for now I'll close this issue as it's not directly an audiolib.js issue.

Thanks for reporting!

**Comment by jussi-kalliokoski** [comment]
Turns out that at least for me installing on OS X was (almost) as simple as the following:

```
git clone https://github.com/kinetiknz/cubeb
cd cubeb
autoreconf --install
./configure
make
make install

npm install cubeb
```

That is, provided the user you're running that with owns `$PREFIX`, which should be the case if you're doing development work on OS X.

However, I had done some stupid stuff myself which broke the install for me initially.

All this said, which version of node are you guys on? node-cubeb doesn't currently work on anything other than 0.8.x, see jussi-kalliokoski/node-cubeb#3 .
